### ISSUE TITLE
[SPRINT] Building TXPipe documentation

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/SprintWeek2020#28]
# Building TXPipe documentation

TXPipe is a great tool, but can be a bit daunting at first, this sprint will aim at setting up a documentation basis that we can build upon progressively. 

Contacts: @EiffL @empEvil @joezuntz 
Day/Time: TBD, probably getting started early in the week
Main communication channel: @desc-3x2pt
GitHub repo: https://github.com/LSSTDESC/TXPipe 

## Goals and deliverable
- [ ] Setup automated doc building on Read The Docs
- [ ] Define strategy for pulling the documentation from individual modules
- [ ] Adding tutorial information in the documentation (e.g. getting started, how to add a new module, how to run the DC2 3x2pt analysis)

## Resources and skills needed
- Skills with python documentation/sphinx. 
- Enthusiasm about the documentation :-) 
- But more importantly, we are **looking for people who might be interested in learning more about TXPipe, and helping build its documentation is a great way to do that.**

## Detailed description

We will be adding documentation based on Sphinx/ReadTheDocs and make sure all of the information is there for new users to get started simply by following the online information.

**Comment by empEvil** [comment]
http://lsstdesc.org/TXPipe/build/html/index.html
