### ISSUE TITLE
[SPRINT] Add functionality for real galsim galaxies + galsim_hub in BTK

### ISSUE THREAD

**Issue by herjy** [LSSTDESC/SprintWeek2020#38]
# Add functionality for real galsim galaxies + galsim_hub in BTK

Enable drawing real galaxy profiles from galsim in the blending toolkit framework (PR [#52](https://github.com/LSSTDESC/BlendingToolKit/pull/52#issue-486261015)).

Contacts: [Rémy Josep](@herjy) , [Ismael Mendoza](@ismael-mendoza )
Day/Time: 8-9am EST (M-W)
Main communication channel: [blending_toolkit](https://lsstc.slack.com/archives/CBXM2G6MP)
GitHub repo: [BlendingToolKit](https://github.com/LSSTDESC/BlendingToolKit), PR [#52](https://github.com/LSSTDESC/BlendingToolKit/pull/52#issue-486261015)
Zoom room: DESC # 16 (see confluence page for link)

## Goals and deliverable
develop a new functionality in BTK to enable realistic galaxy profiles.

## Resources and skills needed
git, python, BTK, galsim.

## Detailed description
The BlendingToolKit allows to draw blends using catalog entries and light profiles generated by the WeakLensingDeblending package. This sprint aims at removing the dependence from WLD with regard to the generation of light profiles and draw profiles directly from galsim using the realistic profiles.

**Comment by ismael-mendoza** [comment]
Success! Functionality will soon be merged into BTK via this branch: https://github.com/LSSTDESC/BlendingToolKit/pull/75. Thanks everyone!
