### ISSUE TITLE
[SPRINT] BTK future development ideas

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/SprintWeek2020#39]
# BTK future development ideas

We will brainstorm ideas for future development of BTK. 

Contacts: @ismael-mendoza, @thuiop
Day/Time: Flexible
Main communication channel: #blending-toolkit
GitHub repo: [BTK](https://github.com/LSSTDESC/BlendingToolKit)

## Goals and deliverable
A couple of detailed issues posted in the BTK github repo.

## Resources and skills needed
btk, galsim, git, DC2 knowledge (bonus)

## Detailed description
Discuss several ideas of things that people are interested in adding to BTK including: 

- Brainstorm DC2 images integration
- BTK documentation update
- update btk_input.py

**Comment by aboucaud** [comment]
Additional ideas that came during the sprint #38 :
- ensure reproducibility of blend images (include a random generator)
- refactor the `btk` module (imports, installation, dependencies, entry points)
- TBC..

**Comment by ismael-mendoza** [comment]
Ideas where all posted in the BTK issue page (https://github.com/LSSTDESC/BlendingToolKit/issues). 
@BastienArcelin would you like to add an issue to simulate DC2 like-images? Not sure when we'll get to it, but it's good to have a record in other people are interested. I remember Francois mentioned it might be easy to simulate them from scratch instead of going through the butler, etc.
