### ISSUE TITLE
[SPRINT] EDI Sprint 2, Townhall follow-up 

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/SprintWeek2020#64]
# Townhall follow-up

We will summarize the notes that were taken during the townhall meeting in the morning to present them at the Sprint close-out session.

Contacts: Katrin Heitmann
Day/Time: Wednesday, 12-1pm PT
Main communication channel: desc-edi
GitHub repo:

## Goals and deliverable
Due to the restricted time during the townhall, the EDI committee decided to go carefully through all the notes taken by the community and summarize them. During this session we will prepare a report to be presented during the sprint close-out and to be posted in the edi channel later. Everybody is welcome to help!

## Resources and skills needed
None

## Detailed description
None

**Comment by ixkael** [comment]
What should be the strategy to work on this? I think there is a lot of overlap/cross-talk between the topics and what people discussed. We could try to edit a copy of the document and 1) move each bullet point into the most relevant section, 2) combine duplicates, 3) compress the language, 4) separate findings from suggestions (which people found difficult to distinguish). 

The copy we can edit is here: [https://docs.google.com/document/d/1HcqIqgqlMFiwpIa8usFQGC7zoOD9JnIYngY5At9IqO4/edit?usp=sharing](https://docs.google.com/document/d/1HcqIqgqlMFiwpIa8usFQGC7zoOD9JnIYngY5At9IqO4/edit?usp=sharing)

**Comment by katrinheitmann** [comment]
Yes, I think rearranging it so we have the most relevant points together and combine duplicates will be very helpful. And compressing language is always good :-) With regard to findings/suggestions, I am hoping that we can report a little bit on what people see being problems (findings) and then hopefully we have some suggestions on how to do things better and we can think about which of those are actually actionable.

**Comment by katrinheitmann** [comment]
Summary: We have had a fruitful Townhall meeting and during the sprint, we summarized some of the discussions in this google doc:  https://docs.google.com/document/d/1HcqIqgqlMFiwpIa8usFQGC7zoOD9JnIYngY5At9IqO4/edit?usp=sharing

Next, the EDI committee is going to try to distill some more concrete action items that the collaboration can follow. For now, we close this Sprint issue. Thanks everybody for joining the effort!
