### ISSUE TITLE
[SPRINT] Cluster Mass modeling Code: CLMM - Come break our code!

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/SprintWeek2020#7]
# CLMM - Come break our code

Test the CLMM package, and find and fix possible problems. Also check the documentation.

**Contacts:** @m-aguena, @combet   
**Day/Time:** There will be an initial tutorial, and three hack sessions.

|  Event | Day | EST | CET | Zoom Room |
| - | - | - | - | - |
| Tutorial | Monday | 9:30 am | 3:30 pm | [10](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Zoom+Sign-Ups) |
| Hack | Tuesday | 9 am | 3 pm | [15](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Zoom+Sign-Ups) |
| Hack | Thursday | 9 am | 3 pm | [wonder.me guadalajara room](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Sprints+Schedule) |
| Hack | Friday | 10 am | 4 pm | [wonder.me guadalajara room](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Sprints+Schedule) |

the links of zoom room can be found [here](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Zoom+Sign-Ups).

**Main communication channel:** #desc-cl-clmassmod
**GitHub repo:** https://github.com/LSSTDESC/CLMM

## Goals and deliverable
Unit tests and bugfixes for the code, new contributors for the project.

## Resources and skills needed
**Technical:** python, some idea on python packages
**Other:** enthusiasm, creativity and destructive power

## Detailed description
As CLMM approaches its first release, we invite newcomers to learn about the code functionality and test drive it.
The first session will be an initial introduction and demonstration of the code. The following sessions will be hands-on, where people can test the code and try to find possible cases that were overlooked. We propose three different possibilities for people to hack on, all will be happening simultaneously on every hack session:
1.  **Find and/or fix code flaws**
    * Play around with the code, see if any bugs come up
    * Check [unit tests](https://github.com/LSSTDESC/CLMM/tree/master/tests)
    * Check the [documentation](http://lsstdesc.org/CLMM/api.html)
2. **Add/improve functionality on the code**
    * Give your opinion on how to improve the code - fill "Hack2 form" [here](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Sprints).
3. **Check current issues**
    * There are also currently pending [issues](https://github.com/LSSTDESC/CLMM/issues)
    * issues marked [good first issue](https://github.com/LSSTDESC/CLMM/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) are especially good for newcomers

**Comment by sylvielsstfr** [comment]
Can you give the permissions ? thanks.

bash: /global/homes/a/aguena/desc/make_clmm_env.sh: Permission denied

Sylvie

**Comment by m-aguena** [comment]
> /global/homes/a/aguena/desc/make_clmm_env.sh

Are you part of the lsst group on nersc? People on the lsst group should have permission

**Comment by m-aguena** [comment]
**[Done on December 1st hack]:**

- Implemented changes suggested on [CLMM PR #331](https://github.com/LSSTDESC/CLMM/pull/331)
