### ISSUE TITLE
[SPRINT] Explore intake as the successor to GCRCatalogs

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/SprintWeek2020#9]
# Explore intake as the successor to GCRCatalogs

Explore the functionalities and features of [intake](https://intake.readthedocs.io/) (https://github.com/intake/intake) and evaluate its potential to become the successor to [GCRCatalogs](https://github.com/LSSTDESC/gcr-catalogs).

Contacts: @yymao @JoanneBogart @heather999 
Day/Time: TBD
Main communication channel: [#desc-gcr-migration](https://lsstc.slack.com/archives/C01DJ017MGD)
GitHub repo: https://github.com/intake/intake, https://github.com/LSSTDESC/gcr-catalogs

## Goals and deliverable
We hope to produce a short note that 
- documents the functionalities and features of [intake](https://intake.readthedocs.io/)
- discusses whether [intake](https://intake.readthedocs.io/) serves our needs to replace [GCRCatalogs](https://github.com/LSSTDESC/gcr-catalogs)
- lists the steps if we are to migrate from [GCRCatalogs](https://github.com/LSSTDESC/gcr-catalogs) to [intake](https://intake.readthedocs.io/) 

## Resources and skills needed
Anyone who has used or plans to use DESC DC2 data products can help! Bonus points for those who are familiar with [GCRCatalogs](https://github.com/LSSTDESC/gcr-catalogs), [pandas](https://pandas.pydata.org/), [dask](https://dask.org/), or [intake](https://intake.readthedocs.io/). 

## Detailed description
intake seems pretty cool :slightly_smiling_face:  Read the blog post here: https://www.anaconda.com/blog/intake-taking-the-pain-out-of-data-access

**Comment by johannct** [comment]
interested

**Comment by yymao** [comment]
Moved to https://github.com/LSSTDESC/gcr-catalogs/issues/570 -- further discussion should go there.
